apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata: 
  name: broker
spec:
  deploymentPlan:
    size: 1
  env:
    - name: ARTEMIS_EXTRA_LIBS
      value: '/amq/init/config/extra-libs'
  brokerProperties:
    - 'storeConfiguration=DATABASE'
    - 'storeConfiguration.jdbcDriverClassName=org.postgresql.Driver'
    - 'storeConfiguration.jdbcConnectionUrl=jdbc:postgresql://postgresql-service.default.svc.cluster.local:5432/postgres?user=postgres&password=postgres'
  acceptors:
  - name: ext-acceptor
    protocols: CORE
    port: 61626
    expose: true
    exposeMode: ingress
    sslEnabled: true
    sslSecret: ext-acceptor-ssl-secret
  console:
    expose: true
  ingressDomain: brus.dev
  resourceTemplates:
    - selector:
        kind: StatefulSet
      patch:
        kind: StatefulSet
        spec:
          template:
            spec:
              initContainers:
                - name: postgresql-jdbc-driver-init
                  image: alpine:latest
                  securityContext:
                    runAsUser: 185
                  volumeMounts:
                    - name: amq-cfg-dir
                      mountPath: /amq/init/config
                  command:
                    - "sh"
                    - "-c"
                    - "mkdir -p /amq/init/config/extra-libs && wget -O /amq/init/config/extra-libs/postgresql-42.7.1.jar https://jdbc.postgresql.org/download/postgresql-42.7.1.jar"
