apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql-container
          image: postgres:16.2
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
          resources:
            limits:
              cpu: 2
              memory: 4Gi
          ports:
            - containerPort: 5432
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: default
spec:
  selector:
    app: postgresql
  ports:
    - name: postgresql-port
      protocol: TCP
      port: 5432
      targetPort: 5432
