apiVersion: v1
kind: Service
metadata: 
  name: ext-acceptor-svc
spec:
  ports:
    - protocol: TCP
      port: 61626
      targetPort: 61626
  selector:
    cluster: jdbc-ha
  type: ClusterIP
  sessionAffinity: None
  publishNotReadyAddresses: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: ext-acceptor-svc-ing
spec:
  tls:
    - hosts:
        - ext-acceptor-svc-ing-default.apps.artemiscloud.io
  rules:
    - host: ext-acceptor-svc-ing-default.apps.artemiscloud.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ext-acceptor-svc
                port:
                  number: 61626
